const ingredients = [
    {"name":"Ability Capsule","type":"Normal","crampower":"40"},
    {"name":"Absorb Bulb","type":"Grass","crampower":"8"},
    {"name":"Adamant Mint","type":"Grass","crampower":"16"},
    {"name":"Adrenaline Orb","type":"Ghost","crampower":"12"},
    {"name":"Aguav Berry","type":"Dragon","crampower":"4"},
    {"name":"Air Balloon","type":"Flying","crampower":"20"},
    {"name":"Amulet Coin","type":"Normal","crampower":"32"},
    {"name":"Apicot Berry","type":"Ground","crampower":"12"},
    {"name":"Armorite Ore","type":"Fighting","crampower":"28"},
    {"name":"Aspear Berry","type":"Ice","crampower":"2"},
    {"name":"Assault Vest","type":"Steel","crampower":"20"},
    {"name":"Babiri Berry","type":"Steel","crampower":"4"},
    {"name":"Balm Mushroom","type":"Grass","crampower":"24"},
    {"name":"Berry Sweet","type":"Fairy","crampower":"30"},
    {"name":"Big Mushroom","type":"Grass","crampower":"14"},
    {"name":"Big Nugget","type":"Ground","crampower":"38"},
    {"name":"Big Pearl","type":"Water","crampower":"12"},
    {"name":"Big Root","type":"Grass","crampower":"8"},
    {"name":"Binding Band","type":"Dark","crampower":"8"},
    {"name":"Black Apricorn","type":"Dark","crampower":"0"},
    {"name":"Black Belt","type":"Fighting","crampower":"14"},
    {"name":"Black Glasses","type":"Dark","crampower":"14"},
    {"name":"Black Sludge","type":"Poison","crampower":"10"},
    {"name":"Blue Apricorn","type":"Water","crampower":"0"},
    {"name":"Blunder Policy","type":"Dark","crampower":"24"},
    {"name":"Bold Mint","type":"Grass","crampower":"16"},
    {"name":"Bottle Cap","type":"Steel","crampower":"40"},
    {"name":"Brave Mint","type":"Grass","crampower":"16"},
    {"name":"Bright Powder","type":"Fairy","crampower":"14"},
    {"name":"Bug Memory","type":"Bug","crampower":"38 or 40"},
    {"name":"Calcium","type":"Fighting","crampower":"4"},
    {"name":"Calm Mint","type":"Grass","crampower":"16"},
    {"name":"Carbos","type":"Fighting","crampower":"4"},
    {"name":"Careful Mint","type":"Grass","crampower":"16"},
    {"name":"Cell Battery","type":"Electric","crampower":"14"},
    {"name":"Charcoal","type":"Fire","crampower":"32"},
    {"name":"Charti Berry","type":"Rock","crampower":"4"},
    {"name":"Cheri Berry","type":"Fire","crampower":"2"},
    {"name":"Chesto Berry","type":"Water","crampower":"2"},
    {"name":"Chilan Berry","type":"Normal","crampower":"4"},
    {"name":"Chipped Pot","type":"Ground","crampower":"36"},
    {"name":"Choice Band","type":"Fighting","crampower":"20"},
    {"name":"Choice Scarf","type":"Normal","crampower":"20"},
    {"name":"Choice Specs","type":"Psychic","crampower":"20"},
    {"name":"Chople Berry","type":"Fighting","crampower":"4"},
    {"name":"Cleanse Tag","type":"Ghost","crampower":"24"},
    {"name":"Clever Feather","type":"Flying","crampower":"6"},
    {"name":"Clover Sweet","type":"Fairy","crampower":"30"},
    {"name":"Coba Berry","type":"Flying","crampower":"4"},
    {"name":"Colbur Berry","type":"Dark","crampower":"4"},
    {"name":"Comet Shard","type":"Ice","crampower":"34"},
    {"name":"Cracked Pot","type":"Ground","crampower":"30"},
    {"name":"Custap Berry","type":"Ghost","crampower":"10"},
    {"name":"Damp Rock","type":"Water","crampower":"12"},
    {"name":"Dark Memory","type":"Dark","crampower":""},
    {"name":"Dawn Stone","type":"Psychic","crampower":"6"},
    {"name":"Destiny Knot","type":"Psychic","crampower":"28"},
    {"name":"Dragon Fang","type":"Dragon","crampower":"18"},
    {"name":"Dragon Memory","type":"Dragon","crampower":""},
    {"name":"Dragon Scale","type":"Dragon","crampower":"18"},
    {"name":"Dubious Disc","type":"Dark","crampower":"32"},
    {"name":"Dusk Stone","type":"Ghost","crampower":"6"},
    {"name":"Dynamax Candy","type":"Dragon","crampower":"6"},
    {"name":"Eject Button","type":"Steel","crampower":"16"},
    {"name":"Eject Pack","type":"Steel","crampower":"16"},
    {"name":"Electric Memory","type":"Electric","crampower":""},
    {"name":"Electric Seed","type":"Electric","crampower":"8"},
    {"name":"Enigma Berry","type":"","crampower":"8 to 12"},
    {"name":"Everstone","type":"Rock","crampower":"20"},
    {"name":"Eviolite","type":"Dragon","crampower":"32"},
    {"name":"Exp. Candy L","type":"Psychic","crampower":"8"},
    {"name":"Exp. Candy M","type":"Psychic","crampower":"6"},
    {"name":"Exp. Candy S","type":"Psychic","crampower":"4"},
    {"name":"Exp. Candy XL","type":"Psychic","crampower":"10"},
    {"name":"Exp. Candy XS","type":"Psychic","crampower":"2"},
    {"name":"Expert Belt","type":"Fighting","crampower":"32"},
    {"name":"Fairy Memory","type":"Fairy","crampower":""},
    {"name":"Fighting Memory","type":"Fighting","crampower":""},
    {"name":"Figy Berry","type":"Fire","crampower":"4"},
    {"name":"Fire Memory","type":"Fire","crampower":""},
    {"name":"Fire Stone","type":"Fire","crampower":"6"},
    {"name":"Flame Orb","type":"Fire","crampower":"14"},
    {"name":"Float Stone","type":"Rock","crampower":"8"},
    {"name":"Flower Sweet","type":"Fairy","crampower":"30"},
    {"name":"Flying Memory","type":"Flying","crampower":""},
    {"name":"Focus Band","type":"Fighting","crampower":"12"},
    {"name":"Focus Sash","type":"Fighting","crampower":"12"},
    {"name":"Fossilized Bird","type":"Electric","crampower":"10"},
    {"name":"Fossilized Dino","type":"Ice","crampower":"10"},
    {"name":"Fossilized Drake","type":"Dragon","crampower":"10"},
    {"name":"Fossilized Fish","type":"Water","crampower":"10"},
    {"name":"Full Incense","type":"Normal","crampower":"2"},
    {"name":"Galarica Cuff","type":"Poison","crampower":"18"},
    {"name":"Galarica Twig","type":"Grass","crampower":"4"},
    {"name":"Ganlon Berry","type":"Ice","crampower":"12"},
    {"name":"Genius Feather","type":"Flying","crampower":"6"},
    {"name":"Gentle Mint","type":"Grass","crampower":"16"},
    {"name":"Ghost Memory","type":"Ghost","crampower":""},
    {"name":"Gold Bottle Cap","type":"Steel","crampower":"40"},
    {"name":"Grass Memory","type":"Grass","crampower":""},
    {"name":"Grassy Seed","type":"Grass","crampower":"8"},
    {"name":"Green Apricorn","type":"Grass","crampower":"0"},
    {"name":"Grepa Berry","type":"Flying","crampower":"6"},
    {"name":"Grip Claw","type":"Bug","crampower":"26"},
    {"name":"Ground Memory","type":"Ground","crampower":""},
    {"name":"Haban Berry","type":"Dragon","crampower":"4"},
    {"name":"Hard Stone","type":"Rock","crampower":"14"},
    {"name":"Hasty Mint","type":"Grass","crampower":"16"},
    {"name":"Health Feather","type":"Flying","crampower":"6"},
    {"name":"Heat Rock","type":"Fire","crampower":"12"},
    {"name":"Heavy-Duty Boots","type":"Ground","crampower":"16"},
    {"name":"Hondew Berry","type":"Ground","crampower":"6"},
    {"name":"Honey","type":"Bug","crampower":"2"},
    {"name":"HP Up","type":"Fighting","crampower":"4"},
    {"name":"Iapapa Berry","type":"Dark","crampower":"4"},
    {"name":"Ice Memory","type":"Ice","crampower":""},
    {"name":"Ice Stone","type":"Ice","crampower":"6"},
    {"name":"Icy Rock","type":"Ice","crampower":"12"},
    {"name":"Impish Mint","type":"Grass","crampower":"16"},
    {"name":"Iron","type":"Fighting","crampower":"4"},
    {"name":"Iron Ball","type":"Steel","crampower":"16"},
    {"name":"Jaboca Berry","type":"Dragon","crampower":"6"},
    {"name":"Jolly Mint","type":"Grass","crampower":"16"},
    {"name":"Kasib Berry","type":"Ghost","crampower":"4"},
    {"name":"Kebia Berry","type":"Poison","crampower":"4"},
    {"name":"Kee Berry","type":"Fairy","crampower":"6"},
    {"name":"Kelpsy Berry","type":"Fighting","crampower":"6"},
    {"name":"King's Rock","type":"Steel","crampower":"32"},
    {"name":"Lagging Tail","type":"Rock","crampower":"10"},
    {"name":"Lansat Berry","type":"Flying","crampower":"10"},
    {"name":"Lax Incense","type":"Psychic","crampower":"2"},
    {"name":"Lax Mint","type":"Grass","crampower":"16"},
    {"name":"Leaf Stone","type":"Grass","crampower":"6"},
    {"name":"Leek","type":"Grass","crampower":"18"},
    {"name":"Leftovers","type":"Grass","crampower":"20"},
    {"name":"Leppa Berry","type":"Fighting","crampower":"2"},
    {"name":"Liechi Berry","type":"Grass","crampower":"12"},
    {"name":"Life Orb","type":"Dragon","crampower":"20"},
    {"name":"Light Ball","type":"Electric","crampower":"20"},
    {"name":"Light Clay","type":"Psychic","crampower":"20"},
    {"name":"Lonely Mint","type":"Grass","crampower":"16"},
    {"name":"Love Sweet","type":"Fairy","crampower":"30"},
    {"name":"Luck Incense","type":"Normal","crampower":"2"},
    {"name":"Lucky Egg","type":"Normal","crampower":"20"},
    {"name":"Lum Berry","type":"Flying","crampower":"2"},
    {"name":"Luminous Moss","type":"Grass","crampower":"8"},
    {"name":"Macho Brace","type":"Fighting","crampower":"26"},
    {"name":"Magnet","type":"Electric","crampower":"20"},
    {"name":"Mago Berry","type":"Ghost","crampower":"4"},
    {"name":"Maranga Berry","type":"Dark","crampower":"6"},
    {"name":"Max Repel","type":"Poison","crampower":"2"},
    {"name":"Mental Herb","type":"Grass","crampower":"14"},
    {"name":"Metal Coat","type":"Steel","crampower":"24"},
    {"name":"Metal Powder","type":"Steel","crampower":"14"},
    {"name":"Metronome","type":"Steel","crampower":"22"},
    {"name":"Micle Berry","type":"Rock","crampower":"10"},
    {"name":"Mild Mint","type":"Grass","crampower":"16"},
    {"name":"Miracle Seed","type":"Grass","crampower":"14"},
    {"name":"Misty Seed","type":"Fairy","crampower":"8"},
    {"name":"Modest Mint","type":"Grass","crampower":"16"},
    {"name":"Moon Stone","type":"Fairy","crampower":"6"},
    {"name":"Muscle Band","type":"Fighting","crampower":"14"},
    {"name":"Muscle Feather","type":"Flying","crampower":"6"},
    {"name":"Mystic Water","type":"Water","crampower":"10"},
    {"name":"Naive Mint","type":"Grass","crampower":"16"},
    {"name":"Naughty Mint","type":"Grass","crampower":"16"},
    {"name":"Never-Melt Ice","type":"Ice","crampower":"14"},
    {"name":"Normal Gem","type":"Normal","crampower":"8"},
    {"name":"Nugget","type":"Ground","crampower":"16"},
    {"name":"Occa Berry","type":"Fire","crampower":"4"},
    {"name":"Odd Incense","type":"Ghost","crampower":"2"},
    {"name":"Oran Berry","type":"Poison","crampower":"2"},
    {"name":"Oval Stone","type":"Rock","crampower":"12"},
    {"name":"Passho Berry","type":"Water","crampower":"4"},
    {"name":"Payapa Berry","type":"Psychic","crampower":"4"},
    {"name":"Pearl","type":"Water","crampower":"6"},
    {"name":"Pearl String","type":"Water","crampower":"30"},
    {"name":"Pecha Berry","type":"Electric","crampower":"2"},
    {"name":"Persim Berry","type":"Ground","crampower":"2"},
    {"name":"Petaya Berry","type":"Poison","crampower":"12"},
    {"name":"Pink Apricorn","type":"Fairy","crampower":"0"},
    {"name":"Pixie Plate","type":"Fairy","crampower":"2"},
    {"name":"Poison Barb","type":"Poison","crampower":"32"},
    {"name":"Poison Memory","type":"Poison","crampower":""},
    {"name":"Pomeg Berry","type":"Ice","crampower":"6"},
    {"name":"Power Anklet","type":"Fighting","crampower":"20"},
    {"name":"Power Band","type":"Fighting","crampower":"20"},
    {"name":"Power Belt","type":"Fighting","crampower":"20"},
    {"name":"Power Bracer","type":"Fighting","crampower":"20"},
    {"name":"Power Herb","type":"Grass","crampower":"10"},
    {"name":"Power Lens","type":"Psychic","crampower":"20"},
    {"name":"Power Weight","type":"Fighting","crampower":"20"},
    {"name":"PP Max","type":"Normal","crampower":"40"},
    {"name":"PP Up","type":"Normal","crampower":"38"},
    {"name":"Pretty Feather","type":"Flying","crampower":"6"},
    {"name":"Prism Scale","type":"Water","crampower":"26"},
    {"name":"Protective Pads","type":"Fighting","crampower":"12"},
    {"name":"Protector","type":"Rock","crampower":"24"},
    {"name":"Protein","type":"Fighting","crampower":"4"},
    {"name":"Psychic Memory","type":"Psychic","crampower":""},
    {"name":"Psychic Seed","type":"Psychic","crampower":"8"},
    {"name":"Pure Incense","type":"Psychic","crampower":"2"},
    {"name":"Qualot Berry","type":"Poison","crampower":"6"},
    {"name":"Quick Claw","type":"Normal","crampower":"26"},
    {"name":"Quick Powder","type":"Normal","crampower":"28"},
    {"name":"Quiet Mint","type":"Grass","crampower":"16"},
    {"name":"Rare Bone","type":"Ground","crampower":"12"},
    {"name":"Rare Candy","type":"Psychic","crampower":"40"},
    {"name":"Rash Mint","type":"Grass","crampower":"16"},
    {"name":"Rawst Berry","type":"Grass","crampower":"2"},
    {"name":"Razor Claw","type":"Dark","crampower":"26"},
    {"name":"Reaper Cloth","type":"Ghost","crampower":"32"},
    {"name":"Red Apricorn","type":"Fire","crampower":"0"},
    {"name":"Red Card","type":"Fire","crampower":"16"},
    {"name":"Relaxed Mint","type":"Grass","crampower":"16"},
    {"name":"Repel","type":"Poison","crampower":"2"},
    {"name":"Resist Feather","type":"Flying","crampower":"6"},
    {"name":"Ribbon Sweet","type":"Fairy","crampower":"30"},
    {"name":"Rindo Berry","type":"Grass","crampower":"4"},
    {"name":"Ring Target","type":"Dark","crampower":"14"},
    {"name":"Rock Incense","type":"Rock","crampower":"2"},
    {"name":"Rock Memory","type":"Rock","crampower":""},
    {"name":"Rocky Helmet","type":"Rock","crampower":"26"},
    {"name":"Room Service","type":"Psychic","crampower":"24"},
    {"name":"Rose Incense","type":"Grass","crampower":"2"},
    {"name":"Roseli Berry","type":"Fairy","crampower":"4"},
    {"name":"Rowap Berry","type":"Dark","crampower":"6"},
    {"name":"Rusted Shield","type":"Steel","crampower":"2 or 4"},
    {"name":"Rusted Sword","type":"Steel","crampower":"2 or 4"},
    {"name":"Sachet","type":"Fairy","crampower":"20"},
    {"name":"Safety Goggles","type":"Normal","crampower":"10"},
    {"name":"Salac Berry","type":"Fighting","crampower":"12"},
    {"name":"Sassy Mint","type":"Grass","crampower":"16"},
    {"name":"Scope Lens","type":"Dark","crampower":"12"},
    {"name":"Sea Incense","type":"Water","crampower":"2"},
    {"name":"Serious Mint","type":"Grass","crampower":"16"},
    {"name":"Sharp Beak","type":"Flying","crampower":"10"},
    {"name":"Shed Shell","type":"Bug","crampower":"10"},
    {"name":"Shell Bell","type":"Water","crampower":"14"},
    {"name":"Shiny Stone","type":"Fairy","crampower":"6"},
    {"name":"Shuca Berry","type":"Ground","crampower":"4"},
    {"name":"Silk Scarf","type":"Normal","crampower":"22"},
    {"name":"Silver Powder","type":"Bug","crampower":"10"},
    {"name":"Sitrus Berry","type":"Psychic","crampower":"2"},
    {"name":"Smoke Ball","type":"Poison","crampower":"22"},
    {"name":"Smooth Rock","type":"Rock","crampower":"12"},
    {"name":"Snowball","type":"Ice","crampower":"8"},
    {"name":"Soft Sand","type":"Ground","crampower":"20"},
    {"name":"Soothe Bell","type":"Steel","crampower":"14"},
    {"name":"Spell Tag","type":"Ghost","crampower":"26"},
    {"name":"Star Piece","type":"Rock","crampower":"20"},
    {"name":"Star Sweet","type":"Fairy","crampower":"30"},
    {"name":"Stardust","type":"Ground","crampower":"8"},
    {"name":"Starf Berry","type":"Psychic","crampower":"10"},
    {"name":"Steel Memory","type":"Steel","crampower":""},
    {"name":"Sticky Barb","type":"Grass","crampower":"10"},
    {"name":"Strawberry Sweet","type":"Fairy","crampower":"30"},
    {"name":"Sun Stone","type":"Fire","crampower":"6"},
    {"name":"Super Repel","type":"Poison","crampower":"2"},
    {"name":"Sweet Apple","type":"Grass","crampower":"30"},
    {"name":"Swift Feather","type":"Flying","crampower":"6"},
    {"name":"Tamato Berry","type":"Psychic","crampower":"6"},
    {"name":"Tanga Berry","type":"Bug","crampower":"4"},
    {"name":"Tart Apple","type":"Grass","crampower":"30"},
    {"name":"Terrain Extender","type":"Ground","crampower":"12"},
    {"name":"Thick Club","type":"Ground","crampower":"18"},
    {"name":"Throat Spray","type":"Water","crampower":"12"},
    {"name":"Thunder Stone","type":"Electric","crampower":"6"},
    {"name":"Timid Mint","type":"Grass","crampower":"16"},
    {"name":"Tiny Mushroom","type":"Grass","crampower":"2"},
    {"name":"Toxic Orb","type":"Poison","crampower":"14"},
    {"name":"Twisted Spoon","type":"Psychic","crampower":"18"},
    {"name":"Upgrade","type":"Normal","crampower":"30"},
    {"name":"Utility Umbrella","type":"Flying","crampower":"20"},
    {"name":"Wacan Berry","type":"Electric","crampower":"4"},
    {"name":"Water Memory","type":"Water","crampower":""},
    {"name":"Water Stone","type":"Water","crampower":"6"},
    {"name":"Wave Incense","type":"Water","crampower":"2"},
    {"name":"Weakness Policy","type":"Dark","crampower":"30"},
    {"name":"Whipped Dream","type":"Fairy","crampower":"26"},
    {"name":"White Apricorn","type":"Normal","crampower":"0"},
    {"name":"White Herb","type":"Grass","crampower":"14"},
    {"name":"Wide Lens","type":"Dark","crampower":"22"},
    {"name":"Wiki Berry","type":"Rock","crampower":"4"},
    {"name":"Wise Glasses","type":"Psychic","crampower":"10 or 12"},
    {"name":"Wishing Piece","type":"Poison","crampower":"28"},
    {"name":"Yache Berry","type":"Ice","crampower":"4"},
    {"name":"Yellow Apricorn","type":"Electric","crampower":"0"},
    {"name":"Zinc","type":"Fighting","crampower":"4"},
    {"name":"Zoom Lens","type":"Dark","crampower":"22"}
];

const recipes = [
    {
        "pool":"Bug",
        "range1":"TR60 (X-Scissor)",
        "range2":"TR18 (Leech Life)",
        "range3":"Bright Powder",
        "range4":"Wishing Piece",
        "range5":"Silver Powder",
        "range6":"Balm Mushroom",
        "range7":"TR61 (Bug Buzz)",
        "range8":"Shed Shell",
        "range9":"Pearl String",
        "range10":"TR96 (Pollen Puff)",
        "range11":"Comet Shard",
        "range12":"TR28 (Megahorn)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Dark",
        "range1":"TR37 (Taunt)",
        "range2":"Wide Lens",
        "range3":"TR68 (Nasty Plot)",
        "range4":"Wishing Piece",
        "range5":"Star Piece",
        "range6":"Balm Mushroom",
        "range7":"TR81 (Foul Play)",
        "range8":"Scope Lens",
        "range9":"TR95 (Throat Chop)",
        "range10":"TR58 (Dark Pulse)",
        "range11":"TR32 (Crunch)",
        "range12":"TR93 (Darkest Lariat)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Dragon",
        "range1":"TR47 (Dragon Claw)",
        "range2":"Dragon Fang",
        "range3":"Big Mushroom",
        "range4":"Wishing Piece",
        "range5":"Star Piece",
        "range6":"Balm Mushroom",
        "range7":"Dragon Scale",
        "range8":"Life Orb",
        "range9":"TR62 (Dragon Pulse)",
        "range10":"King's Rock",
        "range11":"TR51 (Dragon Dance)",
        "range12":"TR24 (Outrage)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Electric",
        "range1":"Electric Seed",
        "range2":"TR80 (Electro Ball)",
        "range3":"Cell Battery",
        "range4":"Wishing Piece",
        "range5":"Magnet",
        "range6":"TR86 (Wild Charge)",
        "range7":"Upgrade",
        "range8":"Light Ball",
        "range9":"Pearl String",
        "range10":"Dubious Disc",
        "range11":"TR08 (Thunderbolt)",
        "range12":"TR09 (Thunder)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Fairy",
        "range1":"Stardust",
        "range2":"Misty Seed",
        "range3":"Big Mushroom",
        "range4":"Wishing Piece",
        "range5":"Sachet",
        "range6":"Room Service",
        "range7":"Whipped Dream",
        "range8":"Destiny Knot",
        "range9":"<sweet_rewards1>",
        "range10":"TR92 (Dazzling Gleam)",
        "range11":"<sweet_rewards2>",
        "range12":"TR90 (Play Rough)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Fighting",
        "range1":"TR07 (Low Kick)",
        "range2":"TR56 (Aura Sphere)",
        "range3":"Muscle Band",
        "range4":"Wishing Piece",
        "range5":"TR48 (Bulk Up)",
        "range6":"TR21 (Reversal)",
        "range7":"Macho Brace",
        "range8":"TR99 (Body Press)",
        "range9":"Expert Belt",
        "range10":"TR64 (Focus Blast)",
        "range11":"TR39 (Superpower)",
        "range12":"TR53 (Close Combat)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Fire",
        "range1":"TR88 (Heat Crash)",
        "range2":"Flame Orb",
        "range3":"TR41 (Blaze Kick)",
        "range4":"Wishing Piece",
        "range5":"TR02 (Flamethrower)",
        "range6":"Balm Mushroom",
        "range7":"TR36 (Heat Wave)",
        "range8":"Red Card",
        "range9":"TR15 (Fire Blast)",
        "range10":"Charcoal",
        "range11":"TR55 (Flare Blitz)",
        "range12":"TR43 (Overheat)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Flying",
        "range1":"Pretty Feather",
        "range2":"Sharp Beak",
        "range3":"Big Mushroom",
        "range4":"Wishing Piece",
        "range5":"Air Balloon",
        "range6":"Blunder Policy",
        "range7":"Grip Claw",
        "range8":"Air Balloon",
        "range9":"Weakness Policy",
        "range10":"TR89 (Hurricane)",
        "range11":"Comet Shard",
        "range12":"TR66 (Brave Bird)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Ghost",
        "range1":"Odd Incense",
        "range2":"Adrenaline Orb",
        "range3":"Ring Target",
        "range4":"Wishing Piece",
        "range5":"Star Piece",
        "range6":"Balm Mushroom",
        "range7":"Cleanse Tag",
        "range8":"Spell Tag",
        "range9":"Cracked Pot",
        "range10":"Reaper Cloth",
        "range11":"Comet Shard",
        "range12":"TR33 (Shadow Ball)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Grass",
        "range1":"Grassy Seed",
        "range2":"TR59 (Seed Bomb)",
        "range3":"White Herb",
        "range4":"Wishing Piece",
        "range5":"TR77 (Grass Knot)",
        "range6":"TR50 (Leaf Blade)",
        "range7":"TR65 (Energy Ball)",
        "range8":"Absorb Bulb",
        "range9":"Pearl String",
        "range10":"TR72 (Power Whip)",
        "range11":"Comet Shard",
        "range12":"TR71 (Leaf Storm)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Ground",
        "range1":"Stardust",
        "range2":"TR23 (Spikes)",
        "range3":"Big Mushroom",
        "range4":"Wishing Piece",
        "range5":"Light Clay",
        "range6":"TR87 (Drill Run)",
        "range7":"TR67 (Earth Power)",
        "range8":"Terrain Extender",
        "range9":"Pearl String",
        "range10":"TR94 (High Horsepower)",
        "range11":"Comet Shard",
        "range12":"TR10 (Earthquake)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Ice",
        "range1":"Snowball",
        "range2":"Icy Rock",
        "range3":"Never-Melt Ice",
        "range4":"Wishing Piece",
        "range5":"Star Piece",
        "range6":"Balm Mushroom",
        "range7":"Razor Claw",
        "range8":"Snowball",
        "range9":"Pearl String",
        "range10":"TR05 (Ice Beam)",
        "range11":"Comet Shard",
        "range12":"TR06 (Blizzard)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Normal",
        "range1":"TR85 (Work Up)",
        "range2":"TR14 (Metronome)",
        "range3":"TR26 (Endure)",
        "range4":"TR13 (Focus Energy)",
        "range5":"TR27 (Sleep Talk)",
        "range6":"TR35 (Uproar)",
        "range7":"TR01 (Body Slam)",
        "range8":"TR19 (Tri Attack)",
        "range9":"TR29 (Baton Pass)",
        "range10":"TR30 (Encore)",
        "range11":"TR20 (Substitute)",
        "range12":"TR00 (Swords Dance)",
        "range13":"TR42 (Hyper Voice)",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Poison",
        "range1":"Black Sludge",
        "range2":"Toxic Orb",
        "range3":"TR91 (Venom Drench)",
        "range4":"Wishing Piece",
        "range5":"TR54 (Toxic Spikes)",
        "range6":"Smoke Ball",
        "range7":"TR57 (Poison Jab)",
        "range8":"Quick Powder",
        "range9":"Poison Barb",
        "range10":"TR22 (Sludge Bomb)",
        "range11":"TR78 (Sludge Wave)",
        "range12":"TR73 (Gunk Shot)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Psychic",
        "range1":"TR12 (Agility)",
        "range2":"TR34 (Future Sight)",
        "range3":"TR40 (Skill Swap)",
        "range4":"TR82 (Stored Power)",
        "range5":"TR44 (Cosmic Power)",
        "range6":"TR83 (Ally Switch)",
        "range7":"TR25 (Psyshock)",
        "range8":"TR69 (Zen Headbutt)",
        "range9":"TR17 (Amnesia)",
        "range10":"TR38 (Trick)",
        "range11":"TR49 (Calm Mind)",
        "range12":"TR97 (Psychic Fangs)",
        "range13":"TR11 (Psychic)",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Rock",
        "range1":"Float Stone",
        "range2":"Oval Stone",
        "range3":"Hard Stone",
        "range4":"Wishing Piece",
        "range5":"Everstone",
        "range6":"Protector",
        "range7":"Rocky Helmet",
        "range8":"TR63 (Power Gem)",
        "range9":"Wishing Piece",
        "range10":"Eviolite",
        "range11":"TR76 (Stealth Rock)",
        "range12":"TR75 (Stone Edge)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Steel",
        "range1":"TR31 (Iron Tail)",
        "range2":"TR46 (Iron Defense)",
        "range3":"Metal Powder",
        "range4":"Wishing Piece",
        "range5":"Utility Umbrella",
        "range6":"Metal Coat",
        "range7":"TR52 (Gyro Ball)",
        "range8":"Assault Vest",
        "range9":"TR79 (Heavy Slam)",
        "range10":"Amulet Coin",
        "range11":"TR70 (Flash Cannon)",
        "range12":"TR74 (Iron Head)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    },
    {
        "pool":"Water",
        "range1":"Sea Incense",
        "range2":"TR04 (Surf)",
        "range3":"Shell Bell",
        "range4":"Wishing Piece",
        "range5":"TR16 (Waterfall)",
        "range6":"TR98 (Liquidation)",
        "range7":"Prism Scale",
        "range8":"Mystic Water",
        "range9":"Pearl String",
        "range10":"TR45 (Muddy Water)",
        "range11":"TR84 (Scald)",
        "range12":"TR03 (Hydro Pump)",
        "range13":"Rare Candy",
        "range14":"Bottle Cap",
        "range15":"PP Up"
    }
]
new Vue({
    el: '#app',
    data: {
        ingredients: ingredients,
        recipes: recipes,
        selectedIngredient1: null,
        selectedIngredient2: null,
        selectedIngredient3: null,
        selectedIngredient4: null,
        fusionResult: null
    },
    computed: {
        totalCrampower() {
            console.log("compute crampower");
            let sum = 0;

            if(this.selectedIngredient1 != null) {
                sum += parseInt(this.selectedIngredient1.crampower);
            }
            if(this.selectedIngredient2 != null) {
                sum += parseInt(this.selectedIngredient2.crampower);
            }
            if(this.selectedIngredient3 != null) {
                sum += parseInt(this.selectedIngredient3.crampower);
            }
            if(this.selectedIngredient4 != null) {
                sum += parseInt(this.selectedIngredient4.crampower);
            }

            console.log("total", sum)

            return sum;
        }
    }
})